name: Flatpak

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    name: Build and publish
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    uses: aetherpak/actions/.github/workflows/publish.yml@v3
    with:
      manifest-path: com.deepseek.harness.yml
      arches: x86_64
      oci-repository: ${{ github.repository }}
      remote-name: dsh
      run-linter: false
      upload-bundle: ${{ github.event_name == 'pull_request' }}
      dry-run: ${{ github.event_name == 'pull_request' }}
